spring:
  boot:
    admin:
      client:
        url: http://111.230.171.37:8084
  zipkin:
    base-url: http://111.230.171.37:9411
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://111.230.171.37:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
        
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
