spring:
  application:
    name: poortravel-web-bamui
  boot:
    admin:
      client:
        instance:
          service-url: http://101.200.190.151:8603
          name: poortravel-web-bamui
server:
  port: 8603
