spring:
  application:
    name: poortravel-zuul
  boot:
    admin:
      client:
        url: http://111.230.171.37:8084
        instance:
          service-url: http://111.230.171.37:8769
          name: poortravel-zuul
  zipkin:
    base-url: http://111.230.171.37:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://111.230.171.37:8761/eureka/

zuul:
  routes:
    poortravel-service-admin:
      path: /admin/service/**
      serviceId: poortravel-service-admin
    poortravel-service-posts:
      path: /post/service/**
      serviceId: poortravel-service-posts
    poortravel-service-attraction:
      path: /attraction/service/**
      serviceId: poortravel-service-attraction
    poortravel-service-base:
      path: /base/service/**
      serviceId: poortravel-service-base
    poortravel-service-upload:
      path: /upload/service/**
      serviceId: poortravel-service-upload
    poortravel-web-bamui:
      path: /bamui/web/**
      serviceId: poortravel-web-bamui
    poortravel-service-redis:
      path: /redis/service/**
      serviceId: poortravel-service-redis

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
