spring:
  application:
    name: poortravel-service-redis
  redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
      sentinel:
        master: mymaster
        nodes: 111.230.171.37:26379, 111.230.171.37:26380, 111.230.171.37:26381

server:
  port: 8502

