spring:
  application:
    name: poortravel-zuul
  boot:
    admin:
      client:
        url: http://111.230.171.37:8084
        instance:
          service-url: http://111.230.171.37:8769
          name: poortravel-zuul
  zipkin:
    base-url: http://111.230.171.37:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://111.230.171.37:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
