spring:
  application:
    name: poortravel-service-redis
  boot:
    admin:
      client:
        instance:
          service-url: http://47.101.152.189:8502
          name: poortravel-service-redis
  redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
      sentinel:
        master: mymaster
        nodes: 111.230.171.37:26379, 111.230.171.37:26380, 111.230.171.37:26381
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 47.101.152.189
 
server:
  port: 8502
