spring:
  application:
    name: poortravel-zuul
  boot:
    admin:
      client:
        url: http://111.230.171.37:8084
        instance:
          service-url: http://111.230.171.37:8769
          name: poortravel-zuul
  zipkin:
    base-url: http://111.230.171.37:9411

server:
  port: 8769

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://111.230.171.37:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  routes:
    poortravel-service-admin:
      path: /admin/service/**
      url: http://47.103.198.196:8501
      serviceId: poortravel-service-admin
    poortravel-service-posts:
      path: /post/service/**
      serviceId: poortravel-service-posts
    poortravel-service-attraction:
      path: /attraction/service/**
      url: http://47.103.198.196:8506
      serviceId: poortravel-service-attraction
    poortravel-service-base:
      path: /base/service/**
      serviceId: poortravel-service-base
    poortravel-service-upload:
      path: /upload/service/**
      serviceId: poortravel-service-upload
    poortravel-web-bamui:
      path: /bamui/web/**
      serviceId: poortravel-web-bamui
    poortravel-service-redis:
      path: /redis/service/**
      serviceId: poortravel-service-redis

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
