spring:
  boot:
    admin:
      client:
        url: http://192.168.229.137:8084
  zipkin:
    base-url: http://192.168.229.137:9411
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false

mybatis:
  configuration:
    cache-enabled: true
  type-aliases-package: com.hongpro.poortravel.common.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.229.137:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info