spring:
  boot:
    admin:
      client:
        url: http://192.168.229.137:8084
  zipkin:
    base-url: http://192.168.229.137:9411
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.229.137:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info