spring:
  application:
    name: poortravel-service-upload
  boot:
    admin:
      client:
        instance:
          service-url: http://101.200.190.151:8505
          name: poortravel-service-upload
fastdfs.base.url: http://111.230.171.37:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 111.230.171.37:22122

server:
  port: 8505
