spring:
  application:
    name: poortravel-admin
  zipkin:
    base-url: http://111.230.171.37:9411

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 111.230.171.37
  client:
    serviceUrl:
      defaultZone: http://111.230.171.37:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
