spring:
  application:
    name: poortravel-service-sso
  boot:
    admin:
      client:
        instance:
          service-url: http://47.103.198.196:8503
          name: poortravel-service-sso
  datasource:
    druid:
      url: jdbc:mysql://111.230.171.37:3306/poortravel-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 47.103.198.196
    
server:
  port: 8503

feign:
  hystrix:
    enabled: true
